spring.application.name=auth-service


spring.datasource.url=jdbc:postgresql://localhost:5432/coinhabit_auth
spring.datasource.username=postgres
spring.datasource.password=230171kom


spring.jpa.hibernate.ddl-auto=update 

spring.jpa.show-sql=true
jwt.secret=${JWT_SECRET:8A2F3E485B6D9C1A2F4B7E901A3C5D8F6E2B4A1C3D5F7E9A0B2C4D6E8F1A3B5C}
jwt.expiration=8640000