spring.application.name=auth-service


spring.datasource.url=jdbc:postgresql://localhost:5432/coinhabit_auth
spring.datasource.username=postgres
spring.datasource.password=230171kom


spring.jpa.hibernate.ddl-auto=update 

spring.jpa.show-sql=true